In [1]:
import pandas as pd

In [4]:
string_data=pd.Series(['aardvark','artichoke',np.nan,'avocado'])

In [3]:
import numpy as np

In [5]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [7]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [8]:
string_data[0]=None

In [9]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [10]:
from numpy import nan as NA

In [11]:
data=pd.Series([1,NA,3.5,NA,7])

In [12]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [13]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [15]:
data=pd.DataFrame([[1.,6.5,3.],[1.,NA,NA],
                  [NA,NA,NA],[NA,6.5,3.]])

In [16]:
cleaned=data.dropna()

In [17]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [18]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [19]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [20]:
data[4]=NA

In [21]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [22]:
data.dropna(axis=1,how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [23]:
df=pd.DataFrame(np.random.randn(7,3))

In [24]:
df.iloc[:4,1]=NA

In [25]:
df.iloc[:2,2]=NA

In [26]:
df

0         1         2
0 -0.063931       NaN       NaN
1 -0.184924       NaN       NaN
2 -1.017327       NaN -1.164683
3  0.838386       NaN  0.405415
4  0.819463 -0.212509 -0.794232
5 -0.859870 -0.604681 -1.186577
6  0.635551  0.438223  1.165644

In [27]:
df.dropna()

0         1         2
4  0.819463 -0.212509 -0.794232
5 -0.859870 -0.604681 -1.186577
6  0.635551  0.438223  1.165644

In [28]:
df.dropna(thresh=2)

0         1         2
2 -1.017327       NaN -1.164683
3  0.838386       NaN  0.405415
4  0.819463 -0.212509 -0.794232
5 -0.859870 -0.604681 -1.186577
6  0.635551  0.438223  1.165644

In [29]:
df.fillna(0)

0         1         2
0 -0.063931  0.000000  0.000000
1 -0.184924  0.000000  0.000000
2 -1.017327  0.000000 -1.164683
3  0.838386  0.000000  0.405415
4  0.819463 -0.212509 -0.794232
5 -0.859870 -0.604681 -1.186577
6  0.635551  0.438223  1.165644

In [30]:
df.fillna({1:0.5,2:0})

0         1         2
0 -0.063931  0.500000  0.000000
1 -0.184924  0.500000  0.000000
2 -1.017327  0.500000 -1.164683
3  0.838386  0.500000  0.405415
4  0.819463 -0.212509 -0.794232
5 -0.859870 -0.604681 -1.186577
6  0.635551  0.438223  1.165644

In [31]:
_=df.fillna(0,inplace=True)

In [32]:
df

0         1         2
0 -0.063931  0.000000  0.000000
1 -0.184924  0.000000  0.000000
2 -1.017327  0.000000 -1.164683
3  0.838386  0.000000  0.405415
4  0.819463 -0.212509 -0.794232
5 -0.859870 -0.604681 -1.186577
6  0.635551  0.438223  1.165644

In [33]:
df=pd.DataFrame(np.random.randn(6,3))

In [34]:
df.iloc[2:,1]=NA

In [35]:
df.iloc[4:,2]=NA

In [36]:
df

0         1         2
0  0.716400 -1.227692  0.522332
1 -0.329880 -0.478815  0.509576
2 -2.854184       NaN  0.408997
3 -0.014525       NaN -0.067758
4  0.656529       NaN       NaN
5 -0.003555       NaN       NaN

In [37]:
df.fillna(method='ffill')

0         1         2
0  0.716400 -1.227692  0.522332
1 -0.329880 -0.478815  0.509576
2 -2.854184 -0.478815  0.408997
3 -0.014525 -0.478815 -0.067758
4  0.656529 -0.478815 -0.067758
5 -0.003555 -0.478815 -0.067758

In [38]:
df.fillna(method='ffill',limit=2)

0         1         2
0  0.716400 -1.227692  0.522332
1 -0.329880 -0.478815  0.509576
2 -2.854184 -0.478815  0.408997
3 -0.014525 -0.478815 -0.067758
4  0.656529       NaN -0.067758
5 -0.003555       NaN -0.067758

In [39]:
data=pd.Series([1.,NA,3.5,NA,7])

In [40]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [41]:
data=pd.DataFrame({'k1':['one','two']*3+['two'],
                  'k2':[1,1,2,3,3,4,4]})

In [42]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [43]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [44]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [45]:
data['v1']=range(7)

In [46]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [47]:
data.drop_duplicates(['k1','k2'],keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [49]:
data=pd.DataFrame({'food':['bacon','pulled pork','bacon',
                          'Pastrami','corned beef','Bacon',
                          'Pastrami','honey ham','nova lox'],
                  'ounces':[4,3,12,6,7.5,8,3,5,6]})

In [50]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     Pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [57]:
meat_to_animals={
    'bacon':'pig',
    'pulled pork':'pig',
    'pastrami':'cow',
    'corned beef':'cow',
    'honey ham':'pig',
    'nova lox':'salmon'
    
}

In [52]:
lowercased = data['food'].str.lower()

In [53]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [54]:
data['animal']=lowercased.map(meat_to_animals)

In [55]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     NaN
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     Pastrami     3.0     NaN
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [58]:
data['food'].map(lambda x: meat_to_animals[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [59]:
data=pd.Series([1.,-999.,2.,-999.,-1000.,3.])

In [60]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [61]:
data.replace(-999.,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [62]:
data.replace([-999,-1000],np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [63]:
data.replace([-999,-1000],[np.nan,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [64]:
data.replace({-999:np.nan,-1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [65]:
data = pd.DataFrame(np.arange(12).reshape((3,4)),
                   index=['Ohio','Colorado','New York'],
                   columns=['one','two','three','four'])

In [66]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [67]:
transform=lambda x: x[:4].upper()

In [68]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [69]:
data.index=data.index.map(transform)

In [70]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [71]:
data.rename(index=str.title,columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [72]:
data.rename(index={'OHIO':'INDIANA'},inplace=True)

In [73]:
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

In [74]:
ages=[20,22,25,27,21,23,37,31,61,45,41,32]

In [75]:
bins=[18,25,35,60,100]

In [76]:
cats=pd.cut(ages,bins)

In [77]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [78]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [79]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]]
              closed='right',
              dtype='interval[int64]')

In [80]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [81]:
pd.cut(ages,[18,26,36,61,100],right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [82]:
group_names=['Youth','YoungAdult','MiddleAged','Senior']

In [83]:
pd.cut(ages,bins,labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [84]:
data=np.random.rand(20)

In [85]:
data

array([0.93195287, 0.69616772, 0.11188762, 0.87887081, 0.29008101,
       0.3325153 , 0.69819596, 0.76615784, 0.61122366, 0.03543586,
       0.3375786 , 0.31101443, 0.93872364, 0.02320793, 0.3781916 ,
       0.92941427, 0.69635005, 0.49924196, 0.35823653, 0.47992515])

In [86]:
pd.cut(data,4,precision=2)

[(0.71, 0.94], (0.48, 0.71], (0.022, 0.25], (0.71, 0.94], (0.25, 0.48], ..., (0.71, 0.94], (0.48, 0.71], (0.48, 0.71], (0.25, 0.48], (0.25, 0.48]]
Length: 20
Categories (4, interval[float64]): [(0.022, 0.25] < (0.25, 0.48] < (0.48, 0.71] < (0.71, 0.94]]

In [87]:
data=np.random.randn(1000)

In [88]:
cats=pd.qcut(data,4)

In [89]:
cats

[(-3.401, -0.621], (-0.621, 0.0941], (0.0941, 0.735], (0.735, 3.277], (0.0941, 0.735], ..., (0.0941, 0.735], (-3.401, -0.621], (-3.401, -0.621], (-3.401, -0.621], (-0.621, 0.0941]]
Length: 1000
Categories (4, interval[float64]): [(-3.401, -0.621] < (-0.621, 0.0941] < (0.0941, 0.735] < (0.735, 3.277]]

In [90]:
pd.value_counts(cats)

(0.735, 3.277]      250
(0.0941, 0.735]     250
(-0.621, 0.0941]    250
(-3.401, -0.621]    250
dtype: int64

In [91]:
pd.qcut(data,[0,0.1,0.5,0.9,1.])

[(-3.401, -1.226], (-1.226, 0.0941], (0.0941, 1.37], (0.0941, 1.37], (0.0941, 1.37], ..., (0.0941, 1.37], (-1.226, 0.0941], (-1.226, 0.0941], (-3.401, -1.226], (-1.226, 0.0941]]
Length: 1000
Categories (4, interval[float64]): [(-3.401, -1.226] < (-1.226, 0.0941] < (0.0941, 1.37] < (1.37, 3.277]]

In [92]:
data=pd.DataFrame(np.random.randn(1000,4))

In [93]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.009679     0.010196    -0.045759     0.004341
std       1.010376     1.003715     0.985562     1.005615
min      -2.844396    -2.936496    -3.208685    -3.117643
25%      -0.689863    -0.643902    -0.708172    -0.686451
50%      -0.035737     0.005718    -0.014650     0.001863
75%       0.701003     0.695097     0.627607     0.663660
max       3.535581     2.997934     3.475913     3.353421

In [94]:
col=data[2]

In [95]:
col[np.abs(col)>3]

80    -3.158008
231    3.175655
448   -3.208685
453   -3.133723
937    3.475913
Name: 2, dtype: float64

In [96]:
data[(np.abs(data)>3).any(1)]

0         1         2         3
39  -0.084431  0.199572  1.197435  3.019090
48   3.535581  0.152665  1.636387  0.399470
80   2.323609 -2.088136 -3.158008 -0.740583
231 -1.238883  0.892501  3.175655 -1.381731
423  3.143242 -0.432759  1.752310  0.432817
448  0.333662  0.099130 -3.208685 -1.364372
453  0.057015  0.938673 -3.133723 -0.784925
732  3.287483 -0.903136  1.022701 -0.239197
822 -0.827250 -2.051281  0.287147  3.353421
928  1.383126 -2.123642 -0.787644 -3.117643
937 -0.189481 -0.214967  3.475913 -0.476473

In [97]:
data[np.abs(data)>3]=np.sign(data)*3

In [98]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.008712     0.010196    -0.045910     0.004086
std       1.007315     1.003715     0.981864     1.004082
min      -2.844396    -2.936496    -3.000000    -3.000000
25%      -0.689863    -0.643902    -0.708172    -0.686451
50%      -0.035737     0.005718    -0.014650     0.001863
75%       0.701003     0.695097     0.627607     0.663660
max       3.000000     2.997934     3.000000     3.000000

In [99]:
np.sign(data).head()

0    1    2    3
0 -1.0  1.0  1.0 -1.0
1 -1.0 -1.0 -1.0 -1.0
2 -1.0  1.0 -1.0  1.0
3  1.0  1.0  1.0  1.0
4  1.0 -1.0 -1.0  1.0

In [100]:
df=pd.DataFrame(np.arange(5*4).reshape((5,4)))

In [101]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [104]:
sampler=np.random.permutation(5)

In [105]:
sampler

array([3, 4, 0, 2, 1])

In [106]:
df.take(sampler)

0   1   2   3
3  12  13  14  15
4  16  17  18  19
0   0   1   2   3
2   8   9  10  11
1   4   5   6   7

In [107]:
df.sample(n=3)

0   1   2   3
0   0   1   2   3
4  16  17  18  19
1   4   5   6   7

In [115]:
choices = pd.Series([5,7,7,7,7,7,7,-1,6,4])

In [109]:
draws=choices.sample(n=10,replace=True)

In [110]:
draws

2   -1
2   -1
0    5
0    5
0    5
1    7
1    7
0    5
1    7
4    4
dtype: int64

In [116]:
draws=choices.sample(n=3,replace=False)

In [117]:
draws

2    7
1    7
5    7
dtype: int64

In [118]:
df=pd.DataFrame({'key':['b','b','a','c','a','b'],
                'data1':range(6)})

In [119]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [120]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [121]:
dummies = pd.get_dummies(df['key'],prefix='key')

In [122]:
df_with_dummy = df[['data1']].join(dummies)

In [124]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [125]:
mnames=['movie_id','title','genres']

In [127]:
movies = pd.read_table('C:/Users/MissEthel/Desktop/python_data_analysis/python_data_analysis/ch07/movielens/movies.dat',
                      sep='::',header=None,names=mnames)

C:\Users\MissEthel\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  


In [128]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [129]:
all_genres=[]

In [130]:
for x in movies.genres:
    all_genres.extend(x.split('|'))

In [131]:
genres  =pd.unique(all_genres)

In [132]:
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [134]:
zero_matrix=np.zeros((len(movies),len(genres)))

In [135]:
dummies = pd.DataFrame(zero_matrix,columns=genres)

In [150]:
gen=movies.genres[0]

In [151]:
gen

"Animation|Children's|Comedy"

In [137]:
gen.split('|')

['Animation', "Children's", 'Comedy']

In [152]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2], dtype=int64)

In [153]:
for i,gen in enumerate(movies.genres):
    indices=dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i,indices]=1

In [141]:
movies_windic=movies.join(dummies.add_prefix('Genre_'))

In [142]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Adventure                                0
Genre_Fantasy                                  0
Genre_Romance                                  0
Genre_Drama                                    0
Genre_Action                                   0
Genre_Crime                                    0
Genre_Thriller                                 0
Genre_Horror                                   0
Genre_Sci-Fi                                   0
Genre_Documentary                              0
Genre_War                                      0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Film-Noir                                0
Genre_Western       

In [143]:
np.random.seed(12345)

In [144]:
values=np.random.rand(10)

In [145]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [146]:
bins=[0,0.2,0.4,0.6,0.8,1]

In [147]:
pd.get_dummies(pd.cut(values,bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

In [159]:
val='a,b,  guido'

In [160]:
val.split(',')

['a', 'b', '  guido']

In [161]:
pieces=[x.strip() for x in val.split(',')]

In [162]:
pieces

['a', 'b', 'guido']

In [164]:
first,  second, third =pieces

In [165]:
first+'::'+second+'::'+third

'a::b::guido'

In [166]:
'::'.join(pieces)

'a::b::guido'

In [167]:
'guido' in val

True

In [168]:
val.index(',')

1

In [169]:
val.find(':')

-1

In [170]:
val.index(':')

ValueError: substring not found

In [171]:
val.count(',')

2

In [174]:
val.replace(',',':')

'a:b:  guido'

In [175]:
val.replace(',','')

'ab  guido'

In [176]:
import re

In [177]:
text ='foo bar\t baz \tqux'

In [178]:
re.split('\s+',text)

['foo', 'bar', 'baz', 'qux']

In [179]:
regex = re.compile('\s+')

In [180]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [181]:
regex.findall(text)

[' ', '\t ', ' \t']

In [182]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""


In [183]:
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

In [184]:
regex = re.compile(pattern,flags=re.IGNORECASE)

In [185]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [186]:
m=regex.search(text)

In [187]:
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [188]:
text[m.start():m.end()]

'dave@google.com'

In [189]:
print(regex.match(text))

None


In [190]:
print(regex.sub('REDACTED',text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED



In [192]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'

In [193]:
regex = re.compile(pattern,flags=re.IGNORECASE)

In [194]:
m=regex.match('wesm@bright.net')

In [195]:
m.groups()

('wesm', 'bright', 'net')

In [196]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [197]:
print(regex.sub(r'Username:\1,Domain:\2,Suffix:\3',text))

Dave Username:dave,Domain:google,Suffix:com
Steve Username:steve,Domain:gmail,Suffix:com
Rob Username:rob,Domain:gmail,Suffix:com
Ryan Username:ryan,Domain:yahoo,Suffix:com



In [198]:
data = {'Dave': 'dave@google.com',
'Steve': 'steve@gmail.com',
'Rob': 'rob@gmail.com','Wes':np.nan}

In [199]:
data=pd.Series(data)

In [200]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [201]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [202]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [203]:
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [204]:
data.str.findall(pattern,flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [206]:
matches=data.str.match(pattern,flags=re.IGNORECASE)

In [207]:
matches

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [208]:
matches.str.get(1)

Dave    NaN
Steve   NaN
Rob     NaN
Wes     NaN
dtype: float64

In [209]:
matches.str[0]

Dave    NaN
Steve   NaN
Rob     NaN
Wes     NaN
dtype: float64

In [210]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object